# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0158d68a0bb59b44e416e532820317e51b774ff178af18f00f6bf1031bfdd8e70cced07f943887ad7bf6902d1d043c085f9f820c740796c6aa3b776f1553c7d

test:
  secret_key_base: 40bc9ce3cb67a61fd4af4652135c8c381ecf65e937bbda25a9aaa8d43ef3036d34748a8b575dffca560ce8dcb5cea80a6e13ef26b5c29c1027bdbbf9597cf99c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
